version: "3.8"

services:
  hugo:
    image: klakegg/hugo:ext
    container_name: hugo
    ports:
      - "1313:1313"
    volumes:
      - .:/src
    command: server --bind 0.0.0.0 --baseURL http://localhost
